# -*- coding: utf-8 -*-
"""Python DEM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TlnK_lc5NBtOE4-m2dBWomqwU5mjoAn-
"""

import os
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

pip install elevation

import elevation

pip install richdem as rd

import richdem as rd

matplotlib.rcParams['figure.figsize'] = (8, 5.5)

dem_path = os.path.join(os.getcwd(), 'Shasta-30m-DEM.tif')
elevation.clip(bounds=(-122.4, 41.2, -122.1, 41.5), output=dem_path)

shasta_dem = rd.LoadGDAL(dem_path)

plt.imshow(shasta_dem, interpolation='none')
plt.colorbar()
plt.show()

slope = rd.TerrainAttribute(shasta_dem, attrib='slope_riserun')
rd.rdShow(slope, axes=False, cmap='magma', figsize=(8, 5.5))
plt.show()

aspect = rd.TerrainAttribute(shasta_dem, attrib='aspect')
rd.rdShow(aspect, axes=False, cmap='jet', figsize=(8, 5.5))
plt.show()